import "./events";

import type { ServerModule } from "@/platform/registry/server";

import { INVOICE_PDF_MAX_BYTES, INVOICE_PDF_PURPOSE } from "../constants";
import { BILLING_PERMISSIONS } from "../permissions";
import { billingEventHandlers } from "./handlers";
import { billingDigestSection, overdueInvoicesRule } from "./insights";

/** Server contributions of billing, commission & profit/loss (M09). */
export const billingServerModule: ServerModule = {
  key: "billing",
  eventHandlers: billingEventHandlers,
  filePurposes: [
    {
      key: INVOICE_PDF_PURPOSE,
      label: "invoice PDFs",
      maxBytes: INVOICE_PDF_MAX_BYTES,
      allowedTypes: ["application/pdf"],
      // Generated by the server only; nobody uploads them.
      uploadPermission: BILLING_PERMISSIONS.billingManage,
      canRead: (ctx) => ctx.permissions.has(BILLING_PERMISSIONS.billingView),
    },
  ],
  extensions: {
    "notifications.alert-rule": [overdueInvoicesRule],
    "notifications.digest-section": [billingDigestSection],
  },
};
